version: '3.5'
services:
    db: # Banco de dados
        image: postgres
        hostname: db
        network_mode: "host"
        environment:
            POSTGRES_USER: rinhero
            POSTGRES_PASSWORD: 1q2w3e
            POSTGRES_DB: rinhadb
        command: 'postgres -c shared_buffers=256MB -c wal_buffers=64MB -c max_connections=200 -c synchronous_commit=off'
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#        ports:
#            - "5432:5432"
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready" ]
            interval: 5s
            timeout: 5s
            retries: 20
            start_period: 10s
        deploy:
            resources:
                limits:
                    cpus: '0.7'
                    memory: '1GB'

    nginx: # Load Balancer
        image: nginx:latest
        network_mode: "host"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            api1:
                condition: service_started
            api2:
                condition: service_started
        ulimits:
            nproc: 65535
            nofile:
                soft: 1000000
                hard: 1000000
        deploy:
            resources:
                limits:
                    cpus: '0.2'
                    memory: '192MB'

    api1: &app
        build: .
        depends_on:
            db:
                condition: service_healthy
        network_mode: "host"
        environment:
            SERVER_PORT: 8080
            DATABASE_USER: rinhero
            DATABASE_PASSWORD: 1q2w3e
            DATABASE_URL: jdbc:postgresql://localhost:5432/rinhadb
        ulimits:
            nproc: 65535
            nofile:
                soft: 1000000
                hard: 1000000
        deploy:
            resources:
                limits:
                    cpus: '0.3'
                    memory: '928MB'

    api2:
        <<: *app
        environment:
            SERVER_PORT: 8081
