version: '3.5'
services:
    db: # Banco de dados
        image: postgres
        hostname: db
        environment:
            POSTGRES_USER: rinhero
            POSTGRES_PASSWORD: 1q2w3e
            POSTGRES_DB: rinhadb
        command: 'postgres -c shared_buffers=256MB -c max_connections=200 -c synchronous_commit=off'
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - "5432:5432"
        deploy:
            resources:
                limits:
                    cpus: '0.8'
                    memory: '1.2GB'

    nginx: # Load Balancer
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - api1
            - api2
        ports:
            - "9999:9999"
        deploy:
            resources:
                limits:
                    cpus: '0.1'
                    memory: '128MB'
    api1:
        build: .
        depends_on:
            - db
        environment:
            DATABASE_USER: rinhero
            DATABASE_PASSWORD: 1q2w3e
            DATABASE_URL: jdbc:postgresql://db:5432/rinhadb
        deploy:
            resources:
                limits:
                    #cpus: '0.3'
                    memory: '850MB'

    api2:
        build: .
        depends_on:
            - db
        environment:
            DATABASE_USER: rinhero
            DATABASE_PASSWORD: 1q2w3e
            DATABASE_URL: jdbc:postgresql://db:5432/rinhadb
        deploy:
            resources:
                limits:
                    #cpus: '0.3'
                    memory: '850MB'
